import React from 'react';
import {
  Atom,
  BrainCircuit,
  GraduationCap,
  Calculator,
  Zap,
  FlaskConical,
  Dna,
  Languages,
  Target,
  Activity,
  Sparkles,
  TrendingUp,
  Compass,
  UserCheck,
  Dumbbell,
  Award,
  BarChart3,
  Layers,
  CheckCircle2,
  ArrowRight,
  ArrowLeft,
  BookOpen,
  HelpCircle,
  ChevronDown,
  ChevronUp,
  Star,
  Play,
  Users,
  Calendar,
  ShieldCheck,
  Clock,
  FileText,
  Search,
  Check,
  Globe,
  Menu,
  X,
  ExternalLink,
  MessageSquare,
  Lock,
} from 'lucide-react';

interface IconHelperProps {
  name: string;
  className?: string;
  size?: number;
}

export const IconHelper: React.FC<IconHelperProps> = ({ name, className = 'w-5 h-5', size }) => {
  const iconMap: Record<string, React.ElementType> = {
    Atom,
    BrainCircuit,
    GraduationCap,
    Calculator,
    Zap,
    FlaskConical,
    Dna,
    Languages,
    Target,
    Activity,
    Sparkles,
    TrendingUp,
    Compass,
    UserCheck,
    Dumbbell,
    Award,
    BarChart3,
    Layers,
    CheckCircle2,
    ArrowRight,
    ArrowLeft,
    BookOpen,
    HelpCircle,
    ChevronDown,
    ChevronUp,
    Star,
    Play,
    Users,
    Calendar,
    ShieldCheck,
    Clock,
    FileText,
    Search,
    Check,
    Globe,
    Menu,
    X,
    ExternalLink,
    MessageSquare,
    Lock,
  };

  const IconComponent = iconMap[name] || Sparkles;
  return <IconComponent className={className} size={size} />;
};
